// Prototype — English text.
module.exports = {
  nav: { home: "Home", about: "About", services: "What we do", retreats: "Retreats", values: "Values", contact: "Contact" },

  ui: {
    badge: "✦ Prototype · view current site",
    scroll: "scroll",
    menu: "Menu",
    langLabel: "Language",
    footerTag: "Conscious cooking, retreats and guidance in Central Catalonia.",
    footerNote: "Design prototype",
    classicLink: "View the current site",
    form: {
      name: "Your name",
      email: "Your email",
      message: "Tell me what you're looking for (optional)",
      submit: "I'd like to know more",
      sending: "Sending…",
      thanks: "Thank you! Your message has arrived. I'll get back to you very soon.",
      error: "It couldn't be sent. Please write to me directly at eticalab.equilibrium@gmail.com.",
    },
    ctaBand: { title: "Does this resonate?", text: "Tell me what you're looking for and let's find your path together.", btn: "Get in touch" },
  },

  stats: [
    { value: "10", count: true, label: "years as a nomad" },
    { value: "3", count: true, label: "years at sea" },
    { value: "El Bulli", label: "haute cuisine" },
    { value: "Michelin", label: "with René Bajard" },
  ],

  home: {
    metaTitle: "Etica_Lab.Equilibrium — Conscious cooking & retreats",
    metaDesc: "Eating is essential; nourishing yourself is an act of self-love. Conscious cooking, retreats and guidance in Central Catalonia.",
    kicker: "Conscious cooking · Retreats · Central Catalonia",
    titleHtml: "Eating is essential.<br><em>Nourishing yourself</em> is an act of self-love.",
    lead: "A laboratory for living, where you discover your own unique, healthy and ethical way of life. We suggest the questions; you hold the answers.",
    ctaPrimary: "Discover the retreats",
    ctaSecondary: "Get in touch",
    marquee: ["Conscious eating", "Retreats", "Community", "Ethics", "Balance", "Gastronomy"],
    philo: {
      kicker: "The right question",
      title: "We simply suggest a few questions.",
      lead: "At Etica_Lab.Equilibrium we believe the answers lie within us. All it takes is asking the right questions — and one essential ingredient: the courage to decipher yourself intimately, free from preconceived beliefs.",
      question: "Are you ready to find that version of yourself and reveal what truly fits your life?",
      badgeHtml: "Only you<br><em>know</em>",
    },
    about: {
      kicker: "The first nomad of this community",
      title: "Hello, I'm Elisenda.",
      lead: "My life has revolved around gastronomy, humanism and travel. From haute cuisine in restaurants like El Bulli to food chemistry, the sea and, finally, a purpose: to cook as a way of teaching a path on which you discover who you are.",
      link: "Read my full story",
    },
    services: {
      kicker: "What we do",
      title: "A life in balance",
      cards: [
        { title: "Personalised sessions", text: "We cook together, at your home or mine, and work out what suits you and what doesn't: shopping, time, creativity and real balance.", tag: "from €60/month" },
        { title: "Online membership", text: "Virtual group classes to see other points of view and integrate new perspectives, from the comfort of home.", tag: "community" },
        { title: "Different events", text: "Celebrations, weekends with friends, corporate team building and conscious retreats.", tag: "tailor-made" },
        { title: "For the little ones", text: "Food ethics classes for children during the school holidays. Ask us — no commitment.", tag: "for families" },
      ],
      link: "See all services",
    },
    retreats: {
      kicker: "Conscious retreats",
      title: "A weekend in which you finally put yourself first",
      intro: "A place to take refuge and pause. Here you'll find a group, a tribe, and tools to create your own oasis within your own chaos. Together with Emilio Martínez, coach and transpersonal therapist.",
      nextLabel: "Next retreat",
      nextTitle: "Masia les Closanes · Moià",
      cta: "Book your place",
      more: "Discover the retreats",
    },
    quote: { html: "“Let food be your medicine<br>and medicine be your food.”", cite: "Hippocrates" },
    values: {
      kicker: "Mission · Vision · Values",
      title: "What we believe in",
      items: [
        { title: "Gastronomy", text: "Nutrition at every level. The group gathered around the table." },
        { title: "Connection", text: "Real human bridges in a world of throwaway connections." },
        { title: "Relationships", text: "Consent, assertive communication, emotional responsibility and inclusion." },
        { title: "Art", text: "The purest expression of the human soul, in all its forms." },
        { title: "Environmental ethics", text: "The foundation on which everything rests. Without a place for life, nothing else matters." },
        { title: "Spirituality", text: "A search for meaning and connection with something greater. No dogma, no hierarchy." },
      ],
      link: "Our mission and vision",
    },
    pricing: {
      kicker: "Value",
      title: "An honest exchange",
      leadHtml: "The word <em>value</em> comes from the Latin <em>valere</em>: “to be strong”. Prices are indicative — we believe in balance between what we give and what we receive, and in barter when it's needed.",
      items: [
        { title: "1:1 sessions", sub: "Online or in person", price: "€60", unit: "/month" },
        { title: "Team building", sub: "Cooking + ethics as a team", price: "€160", unit: "/person" },
        { title: "Dance & music at the table", sub: "Celebrating life", price: "€50", unit: "/person" },
        { title: "Conscious retreats", sub: "A full weekend", price: "+ info", unit: "" },
      ],
      link: "Services & prices",
    },
    contact: {
      kicker: "Begin your journey",
      titleHtml: "Welcome to<br>Etica_Lab.Equilibrium",
      lead: "We are a very special laboratory where you discover your own unique, healthy and ethical way of life. We simply help you uncover the questions.",
    },
  },

  about: {
    metaTitle: "About — Etica_Lab.Equilibrium",
    metaDesc: "I am simply the first nomad of this community. The story of Elisenda Ferrús Rull.",
    kicker: "About me",
    title: "I am simply the first nomad of this community",
    lead: "My name is Elisenda. My life — both personally and professionally — has revolved around gastronomy, humanism, and travel.",
    body: [
      "In my teens I began a career in haute cuisine, working alongside some of the most prestigious chefs of the time and in the most celebrated restaurants in the world, including El Bulli.",
      "Later, in the restaurant industry, I was lucky enough to open a restaurant in Tallinn the very year Estonia joined the EU, and to work alongside the internationally renowned French chef René Bajard, who holds multiple Michelin stars.",
      "I trained in food chemistry in Barcelona, my home city. I wanted to understand why the ingredients I worked with transformed the way they did under my alchemy. That is where I discovered microbiology — our greatest ally, if you know how to work with it. One of the things that fascinates me most, and in which I place great faith, are the natural probiotics found in traditional cuisines all over the world.",
      "After that, studying at the Universitat Autònoma de Bellaterra, I realised I was too young to spend my life between laboratory walls, and turned my compass once more. I turned towards the sea — one of my greatest passions since childhood. I sailed the Mediterranean and its islands, the Caribbean and its wonderful exotic produce, and worked for prominent families on Park Avenue, in the whirl of the Upper East Side of New York City. It was there I understood I had been chasing a social dream, not my own.",
      "I had my first major emotional crisis when I realised I had everything — and felt empty and alone. I went on to design and build galleys (boat kitchens), discovering an engineering capacity in myself that pleasantly surprised me. I have always loved building and dismantling flat-pack furniture, and a new profession grew from that passion: project manager for a company specialising in the maintenance and installation of galleys. I was running projects on some of the largest vessels in the world — cruise ships. Then COVID arrived, and I lost everything, literally.",
      "That was when I truly hit rock bottom, and began to face the shadows that were rising to meet a reality of global confusion and fear. I stepped away from gastronomy — the great love of my life — believing it was one of those many separations we go through, the kind you let go of with a bitter taste in your mouth. I opened a small toy shop for children in a village in northern Catalonia. Another defeat added to my back, reducing to ash what little remained of that ambitious young woman who had dreamed of her first Michelin star at just 21. Where was the dreamer who had got it wrong so many times?",
    ],
    pull: "Then there was nothing left but to be reborn, like a phoenix from the ashes.",
    after: [
      "I studied neuroscience and, together with my insatiable hunger to understand people — built through ten years as a nomad, three of them at sea — I realised that my purpose is to cook as a way of teaching a path: one on which you discover who you are, and can give yourself what you need and what you desire. Because without both of those things, at least for me, I am never quite whole. And you — are you satisfied with the lifestyle habits you have right now?",
    ],
    cards: [
      { title: "Ethics", text: "In today's world, where stress is a constant and unhealthy eating has become the norm, finding a balance between mind and body is vital. That is exactly where Etica_Lab.Equilibrium comes in. Our laboratory is not just a place to learn to cook — it is a space where you can find harmony between your mind and your body, and begin to question what is right for you and what is not. Because only you know that." },
      { title: "Physical, mental and emotional balance", text: "Self-knowledge and wellbeing have become priorities for many people, who are looking to improve their quality of life through healthy eating that fits naturally into their daily lives. But it is equally important to consider ethics and sustainability in the wellness space. The premises at the foundation of our education have expired: the goals of fifty years ago are not the goals of today. We must learn to question ourselves — and in doing so, create the model that actually works for us." },
    ],
  },

  services: {
    metaTitle: "What we do — Etica_Lab.Equilibrium",
    metaDesc: "Personalised sessions, online membership, events, classes for children and conscious retreats.",
    kicker: "What we do",
    title: "A healthy, balanced way of life",
    lead: "We promote a healthy, balanced lifestyle by asking which values and ethics best define us as people — through conscious eating and connection with nature. Our goal: a whole harmony between body, mind and spirit.",
    rows: [
      { title: "Personalised sessions", tag: "1:1 · online or in person", text: "We meet at your home or mine, and we cook together. From there, you can begin to weave together what works for you and what does not — especially day to day: your shopping, and finding your creative rhythm in the kitchen, so that you achieve a balance that is not just nutritional, but also comfortable and realistic given your time and your skills." },
      { title: "Membership", tag: "virtual group classes", text: "Virtual group sessions allow people to see different perspectives and integrate new points of view into their own values. Interact and learn together from the comfort of home." },
      { title: "Different events", tag: "tailor-made", text: "Celebrations, weekends with friends, corporate team building, conscious retreats… Experiences where good food, conversation and connection come together." },
      { title: "Food ethics classes for the little ones", tag: "school holidays", text: "Discover a different way for your children to make the most of their school holidays. When they have no classes and you still have to go to work — and there are no family members or friends available to help — we have a solution. Every school holiday we prepare activities for them: ask us, with no commitment." },
    ],
    pricing: {
      kicker: "Value",
      title: "An honest exchange",
      quoteHtml: "The word <em>value</em> comes from the Latin <em>valere</em>, meaning “to be strong”. From this root come related meanings of strength, courage, health, and the worth of a thing.",
      items: [
        { title: "Personalised 1:1 sessions", text: "We meet one-to-one, cook together, and talk through what matters most to you and how to arrive at a daily life where you feel at ease with your eating — shopping, style, and time. Online or in person.", price: "from €60/month" },
        { title: "Conscious retreats", text: "Together with my partner Emilio Martínez Coach, we run retreats in which we work in unison to create a space of synergy within the group — giving you practical tools for daily life and a way to support yourself through the more complex situations we all encounter.", price: "See retreats", link: "retreats" },
        { title: "Team building", text: "Sessions in which professional teams build far more genuine connections and more fluid day-to-day communication. Cookery workshops paired with ethical conversations that spark interesting group dynamics.", price: "from €160 p/p" },
        { title: "Dance and music around the table", text: "Bringing together great food, great music and dancing is an ancestral act the world over. Join me for a unique experience celebrating life with the people of your choice — hen and stag dos, birthdays, or even a different kind of farewell. Life is for meeting, and for honouring it properly.", price: "from €50 p/p" },
      ],
      closing: [
        "At Etica_Lab.Equilibrium we believe in the exchange of mutual benefit. The prices shown are entirely indicative: we believe in a meeting that feels satisfying and balanced — a fair exchange of what we each bring and receive. We recognise that people's financial situations vary, so we also offer barter arrangements across everything we do. We approach each case with empathy, and together we find a way to work.",
        "Whenever someone commits to working with us as a client, they bring us something of incalculable richness. In return, we offer a service delivered from a place of integrity, never compromising on our professionalism, our knowledge and our experience. We will never offer a service we do not genuinely believe will be useful, or of real value to you.",
      ],
    },
    free: {
      kicker: "Knowledge for all",
      title: "Knowledge takes up no space",
      text: "I want to share my knowledge as a virtual window. This is a place where I offer my experience, my values and my integrity — with gratitude and vulnerability. I hope you can see it as an act of courage, and that it serves you in your own search for answers.",
    },
  },

  retreats: {
    metaTitle: "Retreats — Etica_Lab.Equilibrium",
    metaDesc: "Conscious retreats in Central Catalonia, and a conscious journey to Mexico in 2026.",
    kicker: "Retreats",
    title: "Conscious retreats",
    lead: "A weekend in which you finally put yourself first. A place to take refuge and step away from the rhythm of everyday life.",
    intro: "Here you will find a group, a community, a tribe. More than a unique and unrepeatable experience, you will leave with tools to take home — so you can create your own oasis within your own chaos.",
    teamKicker: "Who walks with you",
    teamTitle: "Two perspectives, one purpose",
    team: [
      { name: "Elisenda Ferrús Rull", roles: ["Personal chef", "Alchemist", "Nomad", "Burner"] },
      { name: "Emilio Martínez Coach", roles: ["Transpersonal therapist", "NLP coach", "Jungian archetypes", "Dream coaching", "Toltec shamanism"] },
    ],
    statement: "Etica_LAB creates experiences.",
    nextKicker: "Next retreat",
    nextTitle: "Masia les Closanes · Moià",
    cta: "Book your place",
    newsKicker: "2026",
    newsTitle: "We're cooking up something new for 2026",
    newsText: "If you'd like to be part of what's coming, write to me and I'll tell you more.",
    newsCta: "I'd like to know more",
    mexicoKicker: "Conscious journey",
    mexicoTitle: "Mexico 2026",
    mexico: [
      "We are creating — together with a remarkable Mexican astrologer and facilitator — an unforgettable journey. We will share more details as they come together.",
      "Drawing on my own story (ten years as a nomad), I want to offer a way of travelling that nourishes you not only through the gastronomy and culture of a place, but through its people. I am building an experience that gives you a more sensual and vivid perspective — one that helps you grow personally in a way that is holistic, intrinsic, and permanently imprinted in your body.",
      "Because simply placing yourself in a new location allows your most essential self to reveal itself. When we travel, part of us stays behind at the point of departure: the beliefs we built up in our familiar environment seem to dissolve, and your being must expose itself once again to something new. Let yourself be carried into a journey that will shift your perspective on yourself and on the situations of your everyday life. Perspective always helps with the next leap into your new life.",
    ],
    closing1: "We simply suggest some questions;",
    closing2: "only you know the answers!",
  },

  values: {
    metaTitle: "Mission, vision and values — Etica_Lab.Equilibrium",
    metaDesc: "To create reflection, and to walk alongside you until you can answer your own questions.",
    kicker: "Mission · Vision · Values",
    title: "Why Etica_Lab.Equilibrium?",
    lead: "What moves us, where we are heading, and what we believe in.",
    mission: {
      label: "Mission",
      title: "The Fool",
      text: "Since childhood I have felt that there was something greater than myself that needed my attention. I cannot quite explain it, but I suppose my mission, in the end, is this:",
      statement: "To create reflection, and to walk alongside you until you can answer your own questions.",
    },
    vision: {
      label: "Vision",
      title: "A conscious community",
      text1: "In all my travels, what has struck me most is the astonishing variety of ways human beings organise themselves to live together in society. The slowest animal in the world is the group.",
      quote: "A community with an alternative coherence for resolving the conflicts of our time.",
      text2: "When I imagine what a world in balance might look like, a recurring image comes to mind: settlements that draw from their surroundings, where each person contributes and receives in harmony. Where conflict is accepted as part of human nature — placed openly on the table to be managed, so that a balance can be found between different perspectives. Where any authority is horizontal rather than hierarchical. Where the group's priorities are written into agreements that coexist in harmony with the wider society and its institutions — integrating constant change into the living fabric of the families who share that community.",
    },
    valuesLabel: "Values",
    valuesTitle: "What we believe in",
    items: [
      { title: "Gastronomy", text: "The leitmotif around which our work revolves is nutrition at every level. The group gathered around the table and the kitchen creates a perfect space to begin unravelling the knot." },
      { title: "Connection", text: "Building close interpersonal bridges — with one another and with the other — in a world of surface-level, throwaway connections." },
      { title: "Relationships", text: "Consent, assertive communication, emotional responsibility, and inclusion." },
      { title: "Art", text: "The purest expression of the human soul. In all its forms.", extra: "Universal language · Reveals the interior · Transformation · Connection and empathy · Personal process" },
      { title: "Environmental ethics", text: "The foundation on which everything else rests. If we have no place to put life, there is no point in building anything further." },
      { title: "Spirituality", text: "The search for meaning, purpose, and connection with something greater than oneself. Without dogma, without hierarchy." },
    ],
  },

  contact: {
    metaTitle: "Contact — Etica_Lab.Equilibrium",
    metaDesc: "Get in touch: sessions, retreats, events and classes in Central Catalonia.",
    kicker: "Contact",
    title: "Let's talk",
    lead: "Welcome to Etica_Lab.Equilibrium! We are a very special laboratory, where you discover your own unique, healthy and ethical way of life. We simply help you uncover the questions — the answers are yours.",
    formTitle: "Write to me",
    formText: "Tell me what you're looking for — a session, a retreat, an event — and I'll get back to you very soon.",
    detailsTitle: "Where to find us",
    location: "Central Catalonia, Spain",
  },
};
