// Prototype — Spanish text.
module.exports = {
  nav: { home: "Inicio", about: "Sobre mí", services: "Qué hacemos", retreats: "Retiros", values: "Valores", contact: "Contacto" },

  ui: {
    badge: "✦ Prototipo · ver web actual",
    scroll: "desliza",
    menu: "Menú",
    langLabel: "Idioma",
    footerTag: "Cocina consciente, retiros y acompañamiento en la Catalunya Central.",
    footerNote: "Prototipo de diseño",
    classicLink: "Ver la web actual",
    form: {
      name: "Tu nombre",
      email: "Tu email",
      message: "Cuéntame qué buscas (opcional)",
      submit: "Quiero saber más",
      sending: "Enviando…",
      thanks: "¡Gracias! Tu mensaje ha llegado. Te responderé muy pronto.",
      error: "No se ha podido enviar. Escríbeme directamente a eticalab.equilibrium@gmail.com.",
    },
    ctaBand: { title: "¿Te resuena?", text: "Cuéntame qué buscas y encontremos juntos tu camino.", btn: "Escríbeme" },
  },

  stats: [
    { value: "10", count: true, label: "años nómada" },
    { value: "3", count: true, label: "años en el mar" },
    { value: "El Bulli", label: "alta cocina" },
    { value: "Michelin", label: "junto a René Bajard" },
  ],

  home: {
    metaTitle: "Etica_Lab.Equilibrium — Cocina consciente y retiros",
    metaDesc: "Comer es fundamental, nutrirse es un acto de amor propio. Cocina consciente, retiros y acompañamiento en la Catalunya Central.",
    kicker: "Cocina consciente · Retiros · Catalunya Central",
    titleHtml: "Comer es fundamental.<br><em>Nutrirse</em>, un acto de amor propio.",
    lead: "Un laboratorio de vida donde encuentras tu propio y único estilo de vida saludable y ético. Nosotros te sugerimos las preguntas; tú tienes las respuestas.",
    ctaPrimary: "Descubre los retiros",
    ctaSecondary: "Escríbeme",
    marquee: ["Alimentación consciente", "Retiros", "Comunidad", "Ética", "Equilibrio", "Gastronomía"],
    philo: {
      kicker: "La pregunta correcta",
      title: "Nosotros simplemente te sugerimos algunas preguntas.",
      lead: "En Etica_Lab.Equilibrium creemos que las respuestas las tenemos dentro. Sólo hace falta hacerse las preguntas adecuadas y un ingrediente fundamental: coraje para descifrarte de una manera íntima, sin creencias preconcebidas.",
      question: "¿Estás preparado para encontrar esa versión de ti mismo y desvelar aquello que de verdad se ajusta a tu vida?",
      badgeHtml: "Sólo tú<br><em>sabes</em>",
    },
    about: {
      kicker: "La primera nómada de esta comunidad",
      title: "Hola, soy Elisenda.",
      lead: "Mi vida ha girado en torno a la gastronomía, el humanismo y los viajes. De la alta cocina en restaurantes como El Bulli a la química de los alimentos, el mar y, finalmente, un propósito: cocinar para enseñar un camino en el que descubras quién eres.",
      link: "Conoce mi historia completa",
    },
    services: {
      kicker: "Qué hacemos",
      title: "Un estilo de vida en equilibrio",
      cards: [
        { title: "Encuentros personalizados", text: "Cocinamos juntos, en tu casa o la mía, y tejemos qué es para ti y qué no: compras, tiempo, creatividad y equilibrio real.", tag: "desde 60€/mes" },
        { title: "Membresía online", text: "Clases grupales virtuales para ver otros puntos de vista e integrar nuevas perspectivas, desde la comodidad de casa.", tag: "comunidad" },
        { title: "Eventos diferentes", text: "Celebraciones, fines de semana con amigos, team building para empresas y retiros conscientes.", tag: "a medida" },
        { title: "Los más pequeños", text: "Clases de ética alimentaria para peques durante las vacaciones escolares. Pregúntanos sin compromiso.", tag: "en familia" },
      ],
      link: "Ver todos los servicios",
    },
    retreats: {
      kicker: "Retiros conscientes",
      title: "Un fin de semana en el que por fin te priorizas",
      intro: "Un lugar donde refugiarte y hacer un parón. Aquí encuentras un grupo, una tribu y unas herramientas para crear tu oasis en tu propio caos. Junto a Emilio Martínez, coach y terapeuta transpersonal.",
      nextLabel: "Próximo retiro",
      nextTitle: "Masia les Closanes · Moià",
      cta: "Reserva tu plaza",
      more: "Descubre los retiros",
    },
    quote: { html: "“Que la comida sea tu medicina<br>y la medicina sea tu comida.”", cite: "Hipócrates" },
    values: {
      kicker: "Misión · Visión · Valores",
      title: "Aquello en lo que creemos",
      items: [
        { title: "Gastronomía", text: "La nutrición a todos los niveles. El grupo alrededor de la mesa." },
        { title: "Conectar", text: "Puentes interpersonales reales en un mundo de conexiones superfluas." },
        { title: "Relaciones", text: "Consentimiento, comunicación asertiva, responsabilidad afectiva e inclusión." },
        { title: "Arte", text: "La expresión más pura del alma humana, en todas sus formas." },
        { title: "Ética ambiental", text: "La base donde todo puede ser. Sin un lugar para la vida, no hay nada más." },
        { title: "Espiritualidad", text: "Búsqueda de significado y conexión con algo mayor. Sin dogmas ni jerarquías." },
      ],
      link: "Nuestra misión y visión",
    },
    pricing: {
      kicker: "Valor",
      title: "Un intercambio honesto",
      leadHtml: "La palabra <em>valor</em> proviene del latín <em>valere</em>: «ser fuerte». Los precios son orientativos —creemos en el equilibrio entre lo que aportamos y lo que recibimos, y en soluciones de trueque cuando hacen falta.",
      items: [
        { title: "Encuentros 1:1", sub: "Online o presencial", price: "60€", unit: "/mes" },
        { title: "Team building", sub: "Cocina + ética en equipo", price: "160€", unit: "/pers" },
        { title: "Baile y música en la mesa", sub: "Celebrar la vida", price: "50€", unit: "/pers" },
        { title: "Retiros conscientes", sub: "Fin de semana completo", price: "+ info", unit: "" },
      ],
      link: "Servicios y precios",
    },
    contact: {
      kicker: "Empieza tu viaje",
      titleHtml: "Bienvenidos a<br>Etica_Lab.Equilibrium",
      lead: "Somos un laboratorio muy especial donde encuentras tu propio y único estilo de vida saludable y ético. Nosotros sólo te ayudamos a descubrir las preguntas.",
    },
  },

  about: {
    metaTitle: "Sobre mí — Etica_Lab.Equilibrium",
    metaDesc: "Yo sólo soy la primera nómada de esta comunidad. La historia de Elisenda Ferrús Rull.",
    kicker: "Sobre mí",
    title: "Yo sólo soy la primera nómada de esta comunidad",
    lead: "Mi nombre es Elisenda. Mi vida, tanto a nivel personal como profesional, ha girado en torno a la gastronomía, el humanismo y los viajes.",
    body: [
      "En la adolescencia empecé una trayectoria en la alta cocina, trabajando junto a los chefs más prestigiosos del momento y en los restaurantes con más renombre a nivel mundial, como El Bulli.",
      "Después, en el sector de la restauración, tuve la gran suerte de abrir un restaurante en Tallinn el mismo año que Estonia entró en la UE, y de formar parte de un equipo junto a un gran chef francés conocido en todo el mundo, René Bajard, con múltiples «étoiles» Michelin a sus espaldas.",
      "Me formé en química de alimentos en Barcelona, mi ciudad de origen, donde quise descubrir por qué los alimentos que sometía a mi alquimia se transformaban de aquel modo. Ahí descubrí la microbiología, nuestra gran aliada si sabes cómo tratar con ella. Una de las cosas que más me fascinan, y en las que creo fervientemente, son nuestros amigos los probióticos naturales que se encuentran en todas las gastronomías del mundo.",
      "Después, en la Universidad de Bellaterra, me di cuenta de que era demasiado joven para quedarme entre las paredes de un laboratorio y volví a girar mi brújula. Me enfoqué en el mar, otra de las cosas que más me apasionan desde pequeña. Navegué el Mediterráneo y sus islas, el Caribe y sus maravillosos productos exóticos, y trabajé para familias importantes en Park Avenue, en la locura de las calles del Upper East Side de Nueva York. Ahí me di cuenta de que había estado persiguiendo un sueño social y no propio.",
      "Tuve mi primera gran crisis emocional cuando descubrí que lo tenía todo y me sentía vacía y sola. Empecé entonces a diseñar y crear cocinas en embarcaciones, donde mi capacidad ingeniera me sorprendió gratamente. Me encanta montar y desmontar muebles de Ikea, y de ahí nació una nueva profesión: project manager de una empresa de mantenimiento e instalación de galleys (cocinas en embarcaciones). Llevaba proyectos en las embarcaciones más grandes del mundo, los cruceros. Y entonces llegó el COVID y lo perdí literalmente todo.",
      "Ahí sí que toqué fondo, y empecé a ver mis sombras asomándose a una realidad de confusión y miedo global. Dejé la gastronomía a un lado —la que había sido el gran amor de mi vida—, creyendo que era una de tantas separaciones que tenemos en la vida, de esas que dejas ir con un sabor amargo en la boca. Empecé un pequeño negocio de juguetes para niños en un pueblecito del norte de Cataluña. Otra derrota más a mis espaldas, que redujo a cenizas lo poco que quedaba de aquella joven ambiciosa que aspiraba a su primera estrella Michelin con tan solo 21 años. ¿Dónde estaba esa soñadora que se equivocó una y tantas veces?",
    ],
    pull: "Entonces ya solo quedaba renacer como ave Fénix.",
    after: [
      "Estudié Neurociencia y, junto a mi hambre voraz de conocer a los humanos después de todos mis viajes (10 años nómada, 3 de ellos embarcada en el mar), me di cuenta de que mi propósito es cocinar para enseñar un camino en el que descubras quién eres y puedas darte aquello que necesitas y deseas. Porque sin una de estas dos cosas, por lo menos yo, no estoy del todo satisfecha. ¿Y tú? ¿Estás satisfecho con tus hábitos y tu filosofía de vida actuales?",
    ],
    cards: [
      { title: "Ética", text: "En el mundo actual, donde el estrés es una constante y la alimentación poco saludable es la norma, es importante encontrar un equilibrio entre nuestra mente y nuestro cuerpo. Ahí es donde Etica_Lab.Equilibrium entra en juego: nuestro laboratorio no es solo un lugar para aprender a cocinar, sino un espacio donde encontrar la armonía entre tu mente y tu cuerpo, y cuestionarte qué es para ti y qué no. ¡Porque sólo tú lo sabes!" },
      { title: "Equilibrio físico, mental y emocional", text: "El autoconocimiento y el bienestar se han convertido en una prioridad para muchas personas, que buscan mejorar su calidad de vida con una alimentación saludable y compatible con su día a día. Pero también es importante tener en cuenta la ética y la sostenibilidad en el mundo del bienestar. Las premisas de nuestra educación han caducado: los objetivos de hace 50 años no son los de hoy. Debemos aprender a cuestionarnos y crear el modelo que nos funciona." },
    ],
  },

  services: {
    metaTitle: "Qué hacemos — Etica_Lab.Equilibrium",
    metaDesc: "Encuentros personalizados, membresía online, eventos, clases para peques y retiros conscientes.",
    kicker: "Qué hacemos",
    title: "Un estilo de vida saludable y en equilibrio",
    lead: "Promovemos un estilo de vida saludable y equilibrado a través de cuestionarnos qué valores y qué ética nos definen mejor como personas, la alimentación consciente y la conexión con la naturaleza. Nuestro objetivo: una armonía integral entre cuerpo, mente y espíritu.",
    rows: [
      { title: "Encuentros personalizados", tag: "1:1 · online o presencial", text: "Quedamos en mi casa o vengo yo a la tuya y cocinamos juntos. A partir de ahí puedes empezar a tejer qué es para ti y qué no, sobre todo en lo cotidiano: la gestión de las compras o la creatividad a la hora de cocinar en casa, para lograr un equilibrio no sólo nutricional, sino cómodo y realista para tu tiempo y tus conocimientos." },
      { title: "Membresía", tag: "clases grupales virtuales", text: "Las clases grupales virtuales permiten ver otros puntos de vista e integrar nuevas perspectivas a nuestros valores. Interactuar y aprender juntos desde la comodidad de casa." },
      { title: "Eventos diferentes", tag: "a medida", text: "Celebraciones, fines de semana con amigos, team building para empresas, retiros conscientes… Experiencias donde se entrelazan el buen comer, la conversación y la conexión." },
      { title: "Clases de ética alimentaria para los más pequeños", tag: "vacaciones escolares", text: "Descubre una manera diferente de que tus peques aprovechen sus vacaciones. Cuando no tienen clase y tú sí debes ir al trabajo, y no tienes familiares o amigos que puedan ayudarte, aquí tenemos una solución. Todas las vacaciones escolares preparamos actividades para ellos: pregúntanos sin compromiso." },
    ],
    pricing: {
      kicker: "Valor",
      title: "Un intercambio honesto",
      quoteHtml: "La palabra «valor» proviene del latín <em>valere</em>, que significa «ser fuerte». De esta raíz se derivan otros significados relacionados con la fuerza, el coraje, la salud o el precio de una cosa.",
      items: [
        { title: "Encuentros 1:1 personalizados", text: "Un encuentro los dos donde cocinamos juntos y charlamos sobre tu prioridad y cómo llegar a un día a día en el que te sientas tranquilo con tu alimentación. ¡Compras, estilo y tiempo! Online o presencial.", price: "desde 60€/mes" },
        { title: "Retiros conscientes", text: "Junto a mi socio Emilio Martínez Coach realizamos retiros en los que trabajamos al unísono y creamos un espacio de sinergia con el grupo, para que obtengas herramientas útiles y una manera de sostenerte ante las situaciones más complejas de la vida.", price: "Ver retiros", link: "retreats" },
        { title: "Team building", text: "Jornadas en las que los equipos establecen conexiones mucho más reales y una comunicación más fluida en su día a día. Talleres de cocina con coloquios éticos que despiertan sinergias grupales muy interesantes.", price: "desde 160€ p/p" },
        { title: "Baile y música alrededor de la mesa", text: "Entrelazar el buen comer, la buena música y el baile es un acto ancestral en todo el mundo. Acompáñame en una experiencia única para celebrar la vida con quien elijas: despedidas de soltero, cumpleaños o incluso funerales distintos. ¡La vida está para encontrarse y honrarla como es debido!", price: "desde 50€ p/p" },
      ],
      closing: [
        "En Etica_Lab.Equilibrium creemos en el intercambio de beneficios entre las partes. Los precios son totalmente orientativos: creemos en un encuentro satisfactorio y en el equilibrio entre lo que aportamos y lo que recibimos. Sabemos que la situación económica de cada persona es variable, por eso ofrecemos soluciones de trueque en todo lo que hacemos. Miramos tu caso con empatía y juntos encontramos la manera de trabajar.",
        "Cada persona que se implica como cliente nos aporta una riqueza incalculable; por nuestra parte, ofrecemos un servicio desde la coherencia, sin negociar nunca nuestra profesionalidad, conocimientos y experiencia. Nunca daremos un servicio que no veamos útil o con verdadero valor para ti.",
      ],
    },
    free: {
      kicker: "Valor al alcance de todos",
      title: "El saber no ocupa lugar",
      text: "Quiero entregar mi conocimiento en forma de ventana virtual. Os presento un lugar donde expongo mi experiencia, valores y coherencia con mucha gratitud y vulnerabilidad. Espero que puedas verlo como un acto de valentía y que pueda servirte en tu propia búsqueda de respuestas.",
    },
  },

  retreats: {
    metaTitle: "Retiros — Etica_Lab.Equilibrium",
    metaDesc: "Retiros conscientes en la Catalunya Central y un viaje consciente a México en 2026.",
    kicker: "Retiros",
    title: "Retiros conscientes",
    lead: "Un fin de semana en el que por fin te priorizas. Un lugar donde refugiarte y hacer un parón en tu vida cotidiana.",
    intro: "Aquí encontrarás un grupo, una comunidad, una tribu. Además de una experiencia única e irrepetible, te llevarás herramientas para volver y crear tu propio oasis en medio de tu caos.",
    teamKicker: "Quién te acompaña",
    teamTitle: "Dos miradas, un mismo propósito",
    team: [
      { name: "Elisenda Ferrús Rull", roles: ["Chef personal", "Alquimista", "Nómada", "Burner"] },
      { name: "Emilio Martínez Coach", roles: ["Terapeuta transpersonal", "PNL-coach", "Arquetipos junguianos", "Coaching onírico", "Chamanismo tolteca"] },
    ],
    statement: "Etica_LAB crea experiencias.",
    nextKicker: "Próximo retiro",
    nextTitle: "Masia les Closanes · Moià",
    cta: "Reserva tu plaza",
    newsKicker: "2026",
    newsTitle: "Estamos cocinando cositas nuevas para este 2026",
    newsText: "Si te interesa formar parte de lo que viene, escríbeme y te lo cuento.",
    newsCta: "Quiero saber más",
    mexicoKicker: "Viaje consciente",
    mexicoTitle: "México 2026",
    mexico: [
      "Estamos creando, junto a un gran astrólogo y facilitador mexicano, un viaje inolvidable. En cuanto sepamos más, os informamos.",
      "Dada mi historia (10 años nómada), quiero mostrar una manera de viajar que te nutra no solo con su gastronomía y su cultura, sino con la gente del lugar. Estoy creando una experiencia que te dé una perspectiva más sensual y vivaz, y que te ayude a evolucionar en tu crecimiento personal de una manera holística, intrínseca e imborrable.",
      "Porque el solo hecho de mostrarte en un lugar nuevo hace que tu ser más esencial se descubra solo. Cuando viajamos, una parte de nosotros se queda en el punto de partida: las creencias que establecimos en nuestro entorno parecen disiparse, y tu ser debe volver a mostrar su cara frente a lo nuevo. Déjate llevar a un viaje que cambiará tu perspectiva de ti mismo ante las situaciones del día a día. La perspectiva siempre ayuda en tu próximo salto hacia tu nueva vida.",
    ],
    closing1: "Nosotros simplemente te sugerimos algunas preguntas;",
    closing2: "¡sólo tú sabes las respuestas!",
  },

  values: {
    metaTitle: "Misión, visión y valores — Etica_Lab.Equilibrium",
    metaDesc: "Crear reflexión y caminar junto a ti hasta donde tú puedas responder tus dudas.",
    kicker: "Misión · Visión · Valores",
    title: "¿Por qué Etica_Lab.Equilibrium?",
    lead: "Aquello que nos mueve, hacia dónde caminamos y en qué creemos.",
    mission: {
      label: "Misión",
      title: "El loco",
      text: "Desde mi infancia he sentido que había algo mayor que yo, que necesitaba de mi atención. No sé explicarlo, pero supongo que la misión, en definitiva, es:",
      statement: "Crear reflexión y caminar junto a ti hasta donde tú puedas responder tus dudas.",
    },
    vision: {
      label: "Visión",
      title: "Comunidad consciente",
      text1: "En todos mis viajes, lo que más me ha llamado la atención son las múltiples alternativas que existen para que los humanos vivamos en sociedad. El animal más lento del mundo es el grupo.",
      quote: "Una comunidad que tenga una coherencia alternativa a la resolución del conflicto actual.",
      text2: "Cuando pienso en cómo sería un mundo en equilibrio, resurge una imagen de asentamientos que se abastecen de su entorno, donde cada uno aporta y recibe en armonía. Donde el conflicto forma parte de la naturaleza humana y se pone encima de la mesa para gestionarlo y llegar a lugares de balance entre las diferentes perspectivas. Donde, si hay una autoridad, es lineal y no jerárquica. Donde las prioridades del grupo se redactan en estatutos que conviven en armonía con la sociedad y sus instituciones, integrando el cambio constante en la convivencia activa de las familias que forman la comunidad.",
    },
    valuesLabel: "Valores",
    valuesTitle: "Aquello en lo que creemos",
    items: [
      { title: "Gastronomía", text: "El leitmotiv de nuestro trabajo es la nutrición a todos los niveles. El grupo alrededor de la mesa y la cocina crea un espacio perfecto para empezar a desenmarañar la madeja." },
      { title: "Conectar", text: "Crear puentes estrechos interpersonales y con el otro, en un mundo superficial y de conexiones superfluas." },
      { title: "Relaciones", text: "El consentimiento, la comunicación asertiva, la responsabilidad afectiva y la inclusión." },
      { title: "Arte", text: "La expresión más pura del alma humana. En todas sus formas.", extra: "Lenguaje universal · Revela lo interior · Transformación · Conexión y empatía · Proceso personal" },
      { title: "Ética ambiental", text: "La base donde todo puede ser. Si no tenemos dónde poner la vida, no tiene ningún sentido seguir construyendo nada." },
      { title: "Espiritualidad", text: "La búsqueda de significado, propósito y conexión con algo más grande que uno mismo. Sin dogmas ni jerarquías." },
    ],
  },

  contact: {
    metaTitle: "Contacto — Etica_Lab.Equilibrium",
    metaDesc: "Escríbeme: encuentros, retiros, eventos y clases en la Catalunya Central.",
    kicker: "Contacto",
    title: "Hablemos",
    lead: "¡Bienvenidos a Etica_Lab.Equilibrium! Somos un laboratorio muy especial, donde encuentras tu propio y único estilo de vida saludable y ético. Nosotros sólo te ayudamos a descubrir las preguntas: las respuestas son tuyas.",
    formTitle: "Escríbeme",
    formText: "Cuéntame qué buscas —un encuentro, un retiro, un evento— y te responderé muy pronto.",
    detailsTitle: "Dónde encontrarnos",
    location: "Catalunya Central",
  },
};
