// Prototype — French text.
module.exports = {
  nav: { home: "Accueil", about: "À propos", services: "Services", retreats: "Retraites", values: "Valeurs", contact: "Contact" },

  ui: {
    badge: "✦ Prototype · voir le site actuel",
    scroll: "défile",
    menu: "Menu",
    langLabel: "Langue",
    footerTag: "Cuisine consciente, retraites et accompagnement en Catalogne centrale.",
    footerNote: "Prototype de design",
    classicLink: "Voir le site actuel",
    form: {
      name: "Ton nom",
      email: "Ton e-mail",
      message: "Dis-moi ce que tu cherches (facultatif)",
      submit: "Je veux en savoir plus",
      sending: "Envoi…",
      thanks: "Merci ! Ton message est bien arrivé. Je te répondrai très vite.",
      error: "L'envoi a échoué. Écris-moi directement à eticalab.equilibrium@gmail.com.",
    },
    ctaBand: { title: "Cela te parle ?", text: "Dis-moi ce que tu cherches et trouvons ensemble ton chemin.", btn: "Écris-moi" },
  },

  stats: [
    { value: "10", count: true, label: "ans de nomadisme" },
    { value: "3", count: true, label: "ans en mer" },
    { value: "El Bulli", label: "haute cuisine" },
    { value: "Michelin", label: "avec René Bajard" },
  ],

  home: {
    metaTitle: "Etica_Lab.Equilibrium — Cuisine consciente et retraites",
    metaDesc: "Manger est fondamental, se nourrir est un acte d'amour de soi. Cuisine consciente, retraites et accompagnement en Catalogne centrale.",
    kicker: "Cuisine consciente · Retraites · Catalogne centrale",
    titleHtml: "Manger est fondamental.<br><em>Se nourrir</em>, un acte d'amour de soi.",
    lead: "Un laboratoire de vie où tu trouves ton propre style de vie, sain, éthique et unique. Nous te suggérons les questions ; tu détiens les réponses.",
    ctaPrimary: "Découvrir les retraites",
    ctaSecondary: "Écris-moi",
    marquee: ["Alimentation consciente", "Retraites", "Communauté", "Éthique", "Équilibre", "Gastronomie"],
    philo: {
      kicker: "La bonne question",
      title: "Nous te suggérons simplement quelques questions.",
      lead: "Chez Etica_Lab.Equilibrium, nous croyons que les réponses sont en nous. Il suffit de se poser les bonnes questions, avec un ingrédient essentiel : le courage de te déchiffrer intimement, sans croyances préconçues.",
      question: "Es-tu prêt à trouver cette version de toi-même et à révéler ce qui correspond vraiment à ta vie ?",
      badgeHtml: "Toi seul<br><em>le sais</em>",
    },
    about: {
      kicker: "La première nomade de cette communauté",
      title: "Bonjour, je suis Elisenda.",
      lead: "Ma vie a tourné autour de la gastronomie, de l'humanisme et des voyages. De la haute cuisine dans des restaurants comme El Bulli à la chimie des aliments, la mer et, enfin, une raison d'être : cuisiner pour enseigner un chemin où tu découvres qui tu es.",
      link: "Découvrir mon histoire",
    },
    services: {
      kicker: "Ce que nous faisons",
      title: "Une vie en équilibre",
      cards: [
        { title: "Rencontres personnalisées", text: "Nous cuisinons ensemble, chez toi ou chez moi, et démêlons ce qui te convient ou non : courses, temps, créativité et vrai équilibre.", tag: "dès 60€/mois" },
        { title: "Adhésion en ligne", text: "Des cours collectifs en ligne pour découvrir d'autres points de vue et intégrer de nouvelles perspectives, depuis chez toi.", tag: "communauté" },
        { title: "Des événements différents", text: "Célébrations, week-ends entre amis, team building pour les entreprises et retraites conscientes.", tag: "sur mesure" },
        { title: "Pour les plus petits", text: "Des cours d'éthique alimentaire pour les enfants pendant les vacances scolaires. Demande-nous sans engagement.", tag: "en famille" },
      ],
      link: "Voir tous les services",
    },
    retreats: {
      kicker: "Retraites conscientes",
      title: "Un week-end où tu te donnes enfin la priorité",
      intro: "Un lieu pour te réfugier et faire une pause. Ici, tu trouves un groupe, une tribu et des outils pour créer ton oasis au cœur de ton propre chaos. Avec Emilio Martínez, coach et thérapeute transpersonnel.",
      nextLabel: "Prochaine retraite",
      nextTitle: "Masia les Closanes · Moià",
      cta: "Réserve ta place",
      more: "Découvrir les retraites",
    },
    quote: { html: "« Que ton aliment soit ton médicament<br>et ton médicament ton aliment. »", cite: "Hippocrate" },
    values: {
      kicker: "Mission · Vision · Valeurs",
      title: "Ce en quoi nous croyons",
      items: [
        { title: "Gastronomie", text: "La nutrition à tous les niveaux. Le groupe réuni autour de la table." },
        { title: "Connexion", text: "De vrais ponts humains dans un monde de connexions éphémères." },
        { title: "Relations", text: "Consentement, communication assertive, responsabilité affective et inclusion." },
        { title: "Art", text: "L'expression la plus pure de l'âme humaine, sous toutes ses formes." },
        { title: "Éthique environnementale", text: "Le socle de tout. Sans lieu pour la vie, rien d'autre n'a de sens." },
        { title: "Spiritualité", text: "Une quête de sens et de lien avec plus grand que soi. Sans dogme ni hiérarchie." },
      ],
      link: "Notre mission et notre vision",
    },
    pricing: {
      kicker: "Valeur",
      title: "Un échange honnête",
      leadHtml: "Le mot <em>valeur</em> vient du latin <em>valere</em> : « être fort ». Les prix sont indicatifs — nous croyons à l'équilibre entre ce que nous apportons et ce que nous recevons, et au troc quand il le faut.",
      items: [
        { title: "Rencontres 1:1", sub: "En ligne ou en présentiel", price: "60€", unit: "/mois" },
        { title: "Team building", sub: "Cuisine + éthique en équipe", price: "160€", unit: "/pers" },
        { title: "Danse et musique à table", sub: "Célébrer la vie", price: "50€", unit: "/pers" },
        { title: "Retraites conscientes", sub: "Un week-end complet", price: "+ d'infos", unit: "" },
      ],
      link: "Services et tarifs",
    },
    contact: {
      kicker: "Commence ton voyage",
      titleHtml: "Bienvenue chez<br>Etica_Lab.Equilibrium",
      lead: "Nous sommes un laboratoire très particulier où tu trouves ton propre style de vie, sain, éthique et unique. Nous t'aidons seulement à découvrir les questions.",
    },
  },

  about: {
    metaTitle: "À propos — Etica_Lab.Equilibrium",
    metaDesc: "Je ne suis que la première nomade de cette communauté. L'histoire d'Elisenda Ferrús Rull.",
    kicker: "À propos",
    title: "Je ne suis que la première nomade de cette communauté",
    lead: "Je m'appelle Elisenda. Ma vie, tant sur le plan personnel que professionnel, a tourné autour de la gastronomie, de l'humanisme et des voyages.",
    body: [
      "À l'adolescence, j'ai entamé une carrière dans la haute cuisine, aux côtés des chefs les plus prestigieux de l'époque et dans les restaurants les plus renommés au monde, comme El Bulli.",
      "Plus tard, dans la restauration, j'ai eu la grande chance d'ouvrir un restaurant à Tallinn l'année même où l'Estonie est entrée dans l'UE, et de faire partie d'une équipe aux côtés d'un grand chef français connu dans le monde entier, René Bajard, aux multiples « étoiles » Michelin.",
      "Je me suis formée en chimie des aliments à Barcelone, ma ville d'origine, où j'ai voulu comprendre pourquoi les aliments que je soumettais à mon alchimie se transformaient de cette manière. C'est là que j'ai découvert la microbiologie, notre grande alliée si l'on sait la traiter. L'une des choses qui me fascinent le plus, et en laquelle je crois avec ferveur, ce sont nos amis les probiotiques naturels que l'on trouve dans toutes les gastronomies du monde.",
      "Ensuite, à l'Université de Bellaterra, je me suis rendu compte que j'étais trop jeune pour rester entre les murs d'un laboratoire, et j'ai de nouveau fait tourner ma boussole. Je me suis tournée vers la mer, l'une des autres choses qui me passionnent le plus depuis l'enfance. J'ai navigué en Méditerranée et ses îles, dans les Caraïbes et leurs merveilleux produits exotiques, et j'ai travaillé pour des familles importantes à Park Avenue, dans la folie des rues de l'Upper East Side de New York. C'est là que j'ai compris que j'avais poursuivi un rêve social, et non le mien.",
      "J'ai vécu ma première grande crise émotionnelle en découvrant que j'avais tout et que je me sentais vide et seule. J'ai alors commencé à concevoir et à créer des cuisines sur des bateaux, où ma capacité d'ingénieure m'a agréablement surprise. J'adore monter et démonter des meubles Ikea, et une nouvelle profession en est née : cheffe de projet dans une entreprise de maintenance et d'installation de galleys (cuisines de bateaux). Je menais des projets sur les plus grands navires du monde, les paquebots de croisière. Puis la COVID est arrivée et j'ai littéralement tout perdu.",
      "Là, j'ai vraiment touché le fond, et j'ai commencé à voir mes ombres affleurer dans une réalité de confusion et de peur mondiales. J'ai laissé la gastronomie de côté — ce qui avait été le grand amour de ma vie —, croyant que c'était l'une de ces nombreuses séparations que l'on vit, de celles que l'on laisse partir avec un goût amer dans la bouche. J'ai lancé une petite boutique de jouets pour enfants dans un petit village du nord de la Catalogne. Une défaite de plus sur mes épaules, qui a réduit en cendres le peu qui restait de cette jeune femme ambitieuse qui aspirait à sa première étoile Michelin à seulement 21 ans. Où était cette rêveuse qui s'était trompée tant et tant de fois ?",
    ],
    pull: "Il ne restait alors plus qu'à renaître, tel un phénix.",
    after: [
      "J'ai étudié les neurosciences et, avec ma faim vorace de connaître les êtres humains après tous mes voyages (10 ans de nomadisme, dont 3 en mer), j'ai compris que ma raison d'être est de cuisiner pour enseigner un chemin sur lequel tu découvres qui tu es, et où tu peux te donner ce dont tu as besoin et ce que tu désires. Car sans l'une de ces deux choses, moi du moins, je ne suis pas pleinement satisfaite. Et toi ? Es-tu satisfait de tes habitudes et de ta philosophie de vie actuelles ?",
    ],
    cards: [
      { title: "Éthique", text: "Dans le monde actuel, où le stress est une constante et où une alimentation peu saine est la norme, il est important de trouver un équilibre entre notre esprit et notre corps. C'est là qu'Etica_Lab.Equilibrium entre en jeu : notre laboratoire n'est pas seulement un lieu pour apprendre à cuisiner, mais un espace où trouver l'harmonie entre ton esprit et ton corps, et te demander ce qui est fait pour toi et ce qui ne l'est pas. Parce que toi seul le sais !" },
      { title: "Équilibre physique, mental et émotionnel", text: "La connaissance de soi et le bien-être sont devenus une priorité pour beaucoup, qui cherchent à améliorer leur qualité de vie grâce à une alimentation saine et compatible avec leur quotidien. Mais il est aussi important de tenir compte de l'éthique et de la durabilité dans le monde du bien-être. Les prémisses de notre éducation ont expiré : les objectifs d'il y a 50 ans ne sont pas ceux d'aujourd'hui. Nous devons apprendre à nous remettre en question et créer le modèle qui nous convient." },
    ],
  },

  services: {
    metaTitle: "Services — Etica_Lab.Equilibrium",
    metaDesc: "Rencontres personnalisées, adhésion en ligne, événements, cours pour enfants et retraites conscientes.",
    kicker: "Ce que nous faisons",
    title: "Un mode de vie sain et équilibré",
    lead: "Nous promouvons un mode de vie sain et équilibré en nous demandant quelles valeurs et quelle éthique nous définissent le mieux en tant que personnes, à travers une alimentation consciente et la connexion avec la nature. Notre objectif : une harmonie globale entre le corps, l'esprit et l'âme.",
    rows: [
      { title: "Rencontres personnalisées", tag: "1:1 · en ligne ou en présentiel", text: "Nous nous retrouvons chez toi ou chez moi, et nous cuisinons ensemble. À partir de là, tu peux commencer à démêler ce qui te convient et ce qui ne te convient pas, surtout au quotidien : la gestion des courses ou la créativité en cuisine, pour atteindre un équilibre non seulement nutritionnel, mais aussi confortable et réaliste pour ton temps et tes connaissances." },
      { title: "Adhésion", tag: "cours collectifs en ligne", text: "Les cours collectifs en ligne permettent de voir d'autres points de vue et d'intégrer de nouvelles perspectives à nos valeurs. Interagir et apprendre ensemble depuis le confort de chez soi." },
      { title: "Des événements différents", tag: "sur mesure", text: "Célébrations, week-ends entre amis, team building pour les entreprises, retraites conscientes… Des expériences où se mêlent la bonne cuisine, la conversation et la connexion." },
      { title: "Cours d'éthique alimentaire pour les plus petits", tag: "vacances scolaires", text: "Découvre une autre façon pour tes enfants de profiter de leurs vacances. Quand ils n'ont pas classe et que toi, tu dois travailler, sans famille ni amis pour t'aider, nous avons une solution. À chaque vacances scolaires, nous préparons des activités pour eux : demande-nous sans engagement." },
    ],
    pricing: {
      kicker: "Valeur",
      title: "Un échange honnête",
      quoteHtml: "Le mot « valeur » vient du latin <em>valere</em>, qui signifie « être fort ». De cette racine découlent d'autres sens liés à la force, au courage, à la santé ou au prix d'une chose.",
      items: [
        { title: "Rencontres 1:1 personnalisées", text: "Un tête-à-tête où nous cuisinons ensemble et parlons de ta priorité et de la manière d'atteindre un quotidien où tu te sens serein avec ton alimentation. Courses, style et temps ! En ligne ou en présentiel.", price: "dès 60€/mois" },
        { title: "Retraites conscientes", text: "Avec mon associé Emilio Martínez Coach, nous organisons des retraites où nous travaillons à l'unisson pour créer un espace de synergie au sein du groupe, afin que tu obtiennes des outils utiles et une manière de te soutenir face aux situations les plus complexes de la vie.", price: "Voir les retraites", link: "retreats" },
        { title: "Team building", text: "Des journées où les équipes tissent des liens bien plus authentiques et une communication plus fluide au quotidien. Des ateliers de cuisine accompagnés d'échanges éthiques qui font naître des dynamiques de groupe passionnantes.", price: "dès 160€ p/p" },
        { title: "Danse et musique autour de la table", text: "Réunir la bonne cuisine, la bonne musique et la danse est un geste ancestral partout dans le monde. Accompagne-moi pour une expérience unique où célébrer la vie avec qui tu veux : enterrements de vie de garçon ou de jeune fille, anniversaires, ou même des adieux d'un autre genre. La vie est faite pour se rencontrer et l'honorer comme il se doit !", price: "dès 50€ p/p" },
      ],
      closing: [
        "Chez Etica_Lab.Equilibrium, nous croyons en l'échange de bénéfices entre les parties. Les prix sont purement indicatifs : nous croyons en une rencontre satisfaisante et en un juste équilibre entre ce que nous apportons et ce que nous recevons. Nous savons que la situation financière de chacun varie, c'est pourquoi nous proposons des solutions de troc dans tout ce que nous faisons. Nous examinons ton cas avec empathie et, ensemble, nous trouvons une façon de travailler.",
        "Chaque personne qui s'engage avec nous en tant que cliente nous apporte une richesse incalculable ; en retour, nous offrons un service fondé sur la cohérence, sans jamais négocier notre professionnalisme, nos connaissances et notre expérience. Nous ne proposerons jamais un service que nous ne jugeons pas utile ou qui n'apporte pas une réelle valeur pour toi.",
      ],
    },
    free: {
      kicker: "La valeur à la portée de tous",
      title: "Le savoir ne prend pas de place",
      text: "Je veux transmettre mon savoir sous forme de fenêtre virtuelle. Je te présente un espace où j'expose mon expérience, mes valeurs et ma cohérence, avec beaucoup de gratitude et de vulnérabilité. J'espère que tu pourras y voir un acte de courage et que cela pourra t'aider dans ta propre quête de réponses.",
    },
  },

  retreats: {
    metaTitle: "Retraites — Etica_Lab.Equilibrium",
    metaDesc: "Retraites conscientes en Catalogne centrale et un voyage conscient au Mexique en 2026.",
    kicker: "Retraites",
    title: "Retraites conscientes",
    lead: "Un week-end où tu te donnes enfin la priorité. Un lieu pour te réfugier et faire une pause dans ta vie quotidienne.",
    intro: "Ici, tu trouveras un groupe, une communauté, une tribu. Au-delà d'une expérience unique et irremplaçable, tu repartiras avec des outils pour créer ton propre oasis au cœur de ton chaos.",
    teamKicker: "Qui t'accompagne",
    teamTitle: "Deux regards, une même raison d'être",
    team: [
      { name: "Elisenda Ferrús Rull", roles: ["Cheffe personnelle", "Alchimiste", "Nomade", "Burner"] },
      { name: "Emilio Martínez Coach", roles: ["Thérapeute transpersonnel", "Coach PNL", "Archétypes jungiens", "Coaching onirique", "Chamanisme toltèque"] },
    ],
    statement: "Etica_LAB crée des expériences.",
    nextKicker: "Prochaine retraite",
    nextTitle: "Masia les Closanes · Moià",
    cta: "Réserve ta place",
    newsKicker: "2026",
    newsTitle: "Nous préparons de nouvelles choses pour 2026",
    newsText: "Si tu veux faire partie de ce qui arrive, écris-moi et je te raconte.",
    newsCta: "Je veux en savoir plus",
    mexicoKicker: "Voyage conscient",
    mexicoTitle: "Mexique 2026",
    mexico: [
      "Nous créons, avec un grand astrologue et facilitateur mexicain, un voyage inoubliable. Dès que nous en saurons plus, nous vous tiendrons informés.",
      "Compte tenu de mon histoire (10 ans de nomadisme), je veux montrer une manière de voyager qui te nourrit non seulement par sa gastronomie et sa culture, mais aussi par les gens du lieu. Je crée une expérience qui t'offre une perspective plus sensuelle et vive, et qui t'aide à évoluer dans ta croissance personnelle de manière holistique, intrinsèque et ineffaçable.",
      "Car le simple fait de te présenter dans un lieu nouveau permet à ton être le plus essentiel de se révéler de lui-même. Quand nous voyageons, une partie de nous reste au point de départ : les croyances que nous avions établies dans notre environnement semblent se dissiper, et ton être doit de nouveau montrer son visage face à la nouveauté. Laisse-toi porter par un voyage qui changera ta perspective sur toi-même face aux situations du quotidien. La perspective aide toujours à ton prochain saut vers ta nouvelle vie.",
    ],
    closing1: "Nous te suggérons simplement quelques questions ;",
    closing2: "toi seul connais les réponses !",
  },

  values: {
    metaTitle: "Mission, vision et valeurs — Etica_Lab.Equilibrium",
    metaDesc: "Créer de la réflexion et marcher à tes côtés jusqu'à ce que tu puisses répondre à tes propres questions.",
    kicker: "Mission · Vision · Valeurs",
    title: "Pourquoi Etica_Lab.Equilibrium ?",
    lead: "Ce qui nous anime, vers où nous marchons et ce en quoi nous croyons.",
    mission: {
      label: "Mission",
      title: "Le Fou",
      text: "Depuis mon enfance, j'ai senti qu'il y avait quelque chose de plus grand que moi qui réclamait mon attention. Je ne sais pas bien l'expliquer, mais je suppose que ma mission, au fond, est celle-ci :",
      statement: "Créer de la réflexion et marcher à tes côtés jusqu'à ce que tu puisses répondre à tes propres questions.",
    },
    vision: {
      label: "Vision",
      title: "Une communauté consciente",
      text1: "Au fil de tous mes voyages, ce qui m'a le plus frappée, c'est l'incroyable diversité des façons dont les êtres humains s'organisent pour vivre en société. L'animal le plus lent du monde, c'est le groupe.",
      quote: "Une communauté dotée d'une cohérence alternative face à la résolution des conflits actuels.",
      text2: "Quand je pense à ce que serait un monde en équilibre, resurgit une image d'établissements qui s'approvisionnent auprès de leur environnement, où chacun apporte et reçoit en harmonie. Où le conflit fait partie de la nature humaine et se pose ouvertement sur la table pour être géré et parvenir à des points d'équilibre entre les différentes perspectives. Où, s'il y a une autorité, elle est horizontale et non hiérarchique. Où les priorités du groupe sont consignées dans des statuts qui coexistent en harmonie avec la société et ses institutions, en intégrant le changement constant dans la vie commune des familles qui forment la communauté.",
    },
    valuesLabel: "Valeurs",
    valuesTitle: "Ce en quoi nous croyons",
    items: [
      { title: "Gastronomie", text: "Le leitmotiv autour duquel s'articule notre travail, c'est la nutrition à tous les niveaux. Le groupe réuni autour de la table et de la cuisine crée un espace parfait pour commencer à démêler l'écheveau." },
      { title: "Connexion", text: "Créer des ponts interpersonnels étroits — avec les autres et avec l'autre — dans un monde superficiel, fait de connexions éphémères." },
      { title: "Relations", text: "Le consentement, la communication assertive, la responsabilité affective et l'inclusion." },
      { title: "Art", text: "L'expression la plus pure de l'âme humaine. Sous toutes ses formes.", extra: "Langage universel · Révèle l'intérieur · Transformation · Connexion et empathie · Processus personnel" },
      { title: "Éthique environnementale", text: "Le socle sur lequel tout repose. Si nous n'avons nulle part où déposer la vie, il ne sert à rien de continuer à construire quoi que ce soit." },
      { title: "Spiritualité", text: "La quête de sens, de but et de connexion avec quelque chose de plus grand que soi. Sans dogme ni hiérarchie." },
    ],
  },

  contact: {
    metaTitle: "Contact — Etica_Lab.Equilibrium",
    metaDesc: "Écris-moi : rencontres, retraites, événements et cours en Catalogne centrale.",
    kicker: "Contact",
    title: "Parlons-en",
    lead: "Bienvenue chez Etica_Lab.Equilibrium ! Nous sommes un laboratoire très particulier, où tu trouves ton propre style de vie, sain, éthique et unique. Nous t'aidons seulement à découvrir les questions : les réponses t'appartiennent.",
    formTitle: "Écris-moi",
    formText: "Dis-moi ce que tu cherches — une rencontre, une retraite, un événement — et je te répondrai très vite.",
    detailsTitle: "Où nous trouver",
    location: "Catalogne centrale, Espagne",
  },
};
